# Generated by Django 3.2.25 on 2024-09-13 19:01

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_user_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=32),
        ),
    ]
