# Generated by Django 3.2.25 on 2024-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_user_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
