# Generated by Django 3.2.25 on 2024-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('opponent', models.CharField(max_length=100)),
                ('play_against_ai', models.BooleanField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
